dbt_k8_demo:
  outputs:
    default:
      type: bigquery
      dataset: dbt_k8_demo
      fixed_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: PoC BigQuery2Hana
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-impersonate@poc-bq2hana.iam.gserviceaccount.com
